//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//*****************************************************************************

#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>
//#include "DevA.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include <driverlib/pin_map.h>
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/UART.h"
#include "inc/tm4c123gh6pm.h"

//*****************************************************************************
unsigned int count;
char str[3];

void PortFunctionInit(void)
{
//	volatile uint32_t ui32Loop;
//		SYSCTL_RCGC2_R = SYSCTL_RCGC2_GPIOF;
//		ui32Loop = SYSCTL_RCGC2_R;
    //
    // Enable Peripheral Clocks 
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);


    //
    //First open the lock and select the bits we want to modify in the GPIO commit register.
    //
    HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;
    HWREG(GPIO_PORTF_BASE + GPIO_O_CR) = 0x1;

    //
    //Configure PF0 & PF4 for input.
    //
    GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);
		
		GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_4);
		
		GPIO_PORTF_PUR_R |= 0x11; 

}

void GPIOPortF_Handler(void)
{
			GPIO_PORTF_ICR_R |= 0x11;
		
			count++;
			sprintf(str, "%f", count);
			UARTCharPut(UART0_BASE, str[0]); 
			UARTCharPut(UART0_BASE, str[1]); 
			UARTCharPut(UART0_BASE, str[2]);
}
void UART_Init(void)
{
	// UART0 Init
	 SysCtlClockSet(SYSCTL_SYSDIV_4 | SYSCTL_USE_PLL | SYSCTL_OSC_MAIN | SYSCTL_XTAL_16MHZ);
	 SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);
   SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);

   GPIOPinConfigure(GPIO_PA0_U0RX);
   GPIOPinConfigure(GPIO_PA1_U0TX);
   GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);

   UARTConfigSetExpClk(UART0_BASE, SysCtlClockGet(), 115200,(UART_CONFIG_WLEN_8 | UART_CONFIG_STOP_ONE | UART_CONFIG_PAR_NONE));
	
	//UART
	//SysCtlPeripheralEnable(SYSCTL_PERIPH_UART1);
  //SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOB);
  //GPIOPinConfigure(GPIO_PB0_U1RX);
  //GPIOPinConfigure(GPIO_PB1_U1TX);
  //GPIOPinTypeUART(GPIO_PORTB_BASE, GPIO_PIN_0 | GPIO_PIN_1);
	//UARTConfigSetExpClk(UART1_BASE, SysCtlClockGet(), 115200,(UART_CONFIG_WLEN_8 | UART_CONFIG_STOP_ONE | UART_CONFIG_PAR_NONE));
}

void Interrupt_Init(void)
{
	NVIC_EN0_R |= 0x40000000; //Enable Interrupt 30 (GPOIF) on NVIC
	NVIC_PRI7_R &= ~0x00A00000; //Set Priority to 0
	GPIO_PORTF_IM_R |= 0x11; //Enable Interrupt Mask PF0 &PF4
	GPIO_PORTF_IS_R &= ~0x11; // Clear IS bit for edge trigger on PF0
	GPIO_PORTF_IEV_R &= ~0x11; // Enable rising Edge trigger for PF0
}
int main(void)
{
	
	UART_Init();
	Interrupt_Init();
	PortFunctionInit();
	count = 12;
	IntMasterEnable();
	sprintf(str, "%f", count);
	
	while(1)
	{
   SysCtlDelay(3000);
		

	}
}
